# -*- coding: utf-8 -*-
"""M2A1I. Manejo y limpieza de datos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10b1TYM8CoL4jXcJ2VZEmXOUgIrnr7vnQ

**HERRAMIENTAS DE GESTIONAR DATOS**

Utilice la función de df.types para obtener el tipo de dato de los valores de la tabla
"""

import pandas as pd
from google.colab import files

excel=files.upload()
df = pd.read_excel('BD-Inmuebles.xlsx')
df.rename(columns={ 'Precio Venta': 'Precio_venta','Fecha Venta': 'Fecha_venta','Edad del vendedor': 'Edad_del_vendedor'})

"""Identificar tipo de dato"""

df.dtypes

"""Se utilizo la función de df.duplicated().sum() para checar si existían valores duplicados en la cual me comento que o existe ninguno"""

df.duplicated().sum()

"""Se utilizo la función de df3.describe().round(2) para revisar datos estáfisticos, suma, mediana, desviación, min, max

"""

df.describe().round(2)

"""Suma por columna los datos nulos de la tabla se utilizo la función f.isnull()sum()"""

df.isnull().sum()

"""Para consultar si existen espacios en blanco se utilizo la siguiente función

"""

df.isin([" "]).any()

"""Se eliminaron los datos vacíos"""

df.dropna(axis=0, inplace=True)

df.isnull().sum()

"""Se reemplazo los datos correspondientes a piso para unificar la data"""

df.replace({
    "Suelo": "Piso",
    "Pisar": "Piso"
}, inplace=True)
df.tail()

"""Se consulto la informacion de la tabla para verificar la reduccion de las filas y columnas"""

df.tail()
df.info()

"""Acomodar datos de forma organizada de menor a mayor"""

df.nsmallest(len(df),'Referencia', keep='first')

"""**HERRAMIENTAS PARA EXPORTAR DATOS**

Extrai un número de filas y cierto numero de columnas utilizando la posición de los valores
"""

df.iloc[2:4, [1,8]]

"""Extrai una sola fila usando el número de fila"""

df.iloc[9]

"""Extrai filas específicas usando sus etiquetas"""

df.loc[[238]]

"""df.loc[[70,291], ['Tipo','Operación']]

Extrai un rango de filas y columnas usando su
etiquetas
"""

df.loc[70:291, 'Tipo':'Operación']